language: pt
domain: supersimplesadvogados.com.br
url: https://super_simples.github.io

title: "Super Simples Advogados"
subtitle: "Seja optante pelo Simples Nacional, é mais vantajoso e menos oneroso."
description: A simple yet classy theme for your Jekyll website or blog.
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

name: Bruno Pellizzetti
email: contato@integracaocascavel.com.br

markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Facebook
    icon: facebook
    username:
    url: "https://www.facebook.com/supersimplesadv/"
    desc: Adicione-me no Facebook
    share: true

  - name:
    icon:
    username:
    url:
    desc:
    share: false

  - name:
    icon:
    username:
    url:
    desc: Fork me on GitHub
    share: false

  - name:
    icon:
    username:
    url:
    desc: Connect with me on LinkedIn
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Add me to your Circles
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Subscribe on YouTube
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Follow me on Instagram
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Follow me on Pinterest
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Follow me on SoundCloud
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Follow me on Tumblr
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Friend me on Steam
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Follow me on Dribble
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Follow me on Vimeo
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Follow me on Vine
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Share to Reddit
    share: false

  - name:
    icon:
    username: ""
    url: ""
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
